#pragma once

#define MAX_BUFFER_LENGTH 512
#define MAX_PROCESS_ID_LENGTH 16

// dopuni po potrebi
typedef enum FLAGS {
	DATA,
	REGISTRATION,
	REGISTRATION_SUCCESSFUL,
	REGISTRATION_FAILED,
	INTEGRITY_UPDATE
}FLAGS;

typedef struct MESSAGE
{
	char processId[MAX_PROCESS_ID_LENGTH];
	char message[MAX_BUFFER_LENGTH];
	FLAGS flag;
}MESSAGE;